### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by Tokeli** [jmdejong/Asciifarm#25]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tokeli/farm/asciifarm/client/__main__.py", line 10, in <module>
    from . import main
  File "/home/tokeli/farm/asciifarm/client/main.py", line 15, in <module>
    from ratuil.screen import Screen
ModuleNotFoundError: No module named 'ratuil.screen'
```

Looks like the farm hasn't kept up!

**Comment by jmdejong** [comment]
I haven't really been maintaining this anymore since I started the rust server with a separate client:

see [rustifarm](https://github.com/jmdejong/rustifarm) and [asciifarm-client](https://github.com/jmdejong/asciifarm-client) for the more up to date implementations.

I can try to see if this is easy to solve, or otherwise to see if an older ratuil version would work.
I suspect that ratuil 0.1.0 and below should be compatible with this asciifarm repo.

**Comment by RickyZimmermann** [comment]
Too bad. I dont want to use rust 
Do you have a old backup maybe? That source is just not working anymore.

I realy need it in xterm, terminal, termux, or cmd.

**Comment by jmdejong** [comment]
I've included a compatible version of ratuil in the repo so there are no external dependencies anymore
